name: 'Federated Open API Specifiction Release Process (PROD)'
on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 9 * * *'

permissions:
  contents: write


jobs:
  retrieve-oases:
    runs-on: ubuntu-latest
    steps:
      - name: Retrieve OASes from S3 bucket
        env:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_DEV }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
          aws-region: ${{ secrets.AWS_REGION }}
        run: |
          run: aws s3 cp s3://${{ secrets.APIX_DEV_S3_BUCKET_NAME }}/openapi/foas-metadata.json foas-metadata.json
          cat foas-metadata.json
