name: '(PROD) Release FOAS'
on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 9 * * *'
permissions:
  contents: write
jobs:
  validations:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
      - name: Run Spectral
        uses: stoplightio/spectral-action@2ad0b9302e32a77c1caccf474a9b2191a8060d83
        with:
          file_glob: 'tools/cli/test/data/*.{json,yml,yaml}'

      
